package com.fracta7.e_bookshelf.domain.model

object Genres {
    val list = listOf(
        "Fantasy",
        "Science Fiction",
        "Dystopian",
        "Action&Adventure",
        "Mystery",
        "Horror",
        "Thriller&Suspense",
        "Historical Fiction",
        "Romance",
        "Women's Fiction",
        "LGBTQ+",
        "Contemporary Fiction",
        "Literary Fiction",
        "Magical Realism",
        "Graphic Novel",
        "Short Story",
        "Young Adult",
        "New Adult",
        "Children's",
        "Memoir&Autobiography",
        "Biography",
        "Food&Drink",
        "Art&Photography",
        "Self-help",
        "History",
        "Travel",
        "True Crime",
        "Humor",
        "Essays",
        "Guide/How-to",
        "Religion&Spirituality",
        "Humanities&Social Sciences",
        "Parenting&Families",
        "Science&Technology"
    )
}